// packages/vue/src/components/tabs/TabsTrigger.vue
<script setup lang="ts">
import { inject, defineProps, Ref, computed } from 'vue';

const props = defineProps<{
  value: string;
}>();

const activeTab: Ref<string> | undefined = inject('activeTab');

const isActive = computed(() => activeTab?.value === props.value);

function setActive() {
  if (!activeTab) return;

  activeTab.value = props.value;
};
</script>


<template>
  <button :class="isActive && 'bg-white text-black shadow'" class="inline-flex items-center justify-center whitespace-nowrap rounded-md px-3 py-1 text-sm font-medium transition-all outline-none focus-visible:ring-2 focus-visible:ring-black focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50" @click="setActive">
    <slot></slot>
  </button>
</template>

// packages/react/components/tabs/tabs-trigger.tsx
import React from "react";

export interface TabsTriggerProps {
  value: string;
  activeTab: string;
  setActiveTab: (value: string) => void;
  children: React.ReactNode;
}

export default function TabsTrigger(props: TabsTriggerProps) {
  const { value, activeTab, setActiveTab, children } = props;
  const isActive = activeTab === value;

  return (
    <button
      className={[
        "inline-flex items-center justify-center whitespace-nowrap rounded-md px-3 py-1 text-sm font-medium transition-all outline-none focus-visible:ring-2 focus-visible:ring-black focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50",
        isActive && "bg-white text-black shadow",
      ]
        .filter(Boolean)
        .join(" ")}
      onClick={() => setActiveTab(value)}
    >
      {children}
    </button>
  );
}
