// packages/react/components/tarava-builder.tsx
import React, { useRef } from "react";
import { AssetType } from "@tarava/types";
import AvatarRenderer from "./avatar-renderer";
import AssetSelector from "./asset-selector";

import type { Asset, Avatar } from "@tarava/types";
import useTarava from "../hooks/useTarava";

export interface TaravaBuilderProps {
  height: number;
  width: number;
  onSelect: (type: AssetType, asset: Asset, avatar: Avatar) => void;
}

export default function TaravaBuilder(props: TaravaBuilderProps) {
  const { width, height, onSelect } = props;

  const canvas = useRef<HTMLCanvasElement>(null);

  const {
    store,
    setAvatar,
    avatar,
    assets,
    onInit,
    setHeadAsset,
    setEyebrowsAsset,
    setEyesAsset,
    setMouthAsset,
    setNoseAsset,
  } = useTarava(canvas);

  function handleSelect(type: AssetType, asset: Asset) {
    switch (type) {
      case AssetType.HEAD:
        setHeadAsset(asset);
        break;
      case AssetType.EYEBROWS:
        setEyebrowsAsset(asset);
        break;
      case AssetType.EYES:
        setEyesAsset(asset);
        break;
      case AssetType.NOSE:
        setNoseAsset(asset);
        break;
      case AssetType.MOUTH:
        setMouthAsset(asset);
        break;
    }

    if (!avatar) return;

    onSelect?.(type, asset, avatar);
  }

  onInit(() => {
    if (!store || !assets) return;

    setAvatar({
      head: assets.head[0],
      eyebrows: assets.eyebrows[0],
      eyes: assets.eyes[0],
      nose: assets.nose[0],
      mouth: assets.mouth[0],
    });
  });

  return (
    <>
      <AvatarRenderer ref={canvas} width={width} height={height} />
      <AssetSelector
        assets={assets}
        setHeadAsset={setHeadAsset}
        setEyebrowsAsset={setEyebrowsAsset}
        setEyesAsset={setEyesAsset}
        setMouthAsset={setMouthAsset}
        setNoseAsset={setNoseAsset}
        onSelect={handleSelect}
      />
    </>
  );
}

// packages/vue/src/components/TaravaBuilder.vue
<script setup lang="ts">
import { ref, defineProps } from 'vue'
import useTarava from "@/composables/useTarava";
import AvatarRenderer from '@/components/AvatarRenderer.vue';
import AssetSelector from '@/components/AssetSelector.vue';
import { AssetType } from '@tarava/types';

import type { Ref } from 'vue'
import type { Asset, Avatar } from '@tarava/types';

const props = defineProps<{
  height: number
  width: number
}>();

const emit = defineEmits<{
  (e: 'select', type: AssetType, asset: Asset, avatar: Avatar): void
}>()

const canvas = ref<HTMLCanvasElement>()
const { store, setAvatar, avatar, assets, onInit, setHeadAsset, setEyebrowsAsset, setEyesAsset, setMouthAsset, setNoseAsset } = useTarava(canvas as Ref<HTMLCanvasElement>);

function handleSelect(type: AssetType, asset: Asset) {  
  switch (type) {
    case AssetType.HEAD:
      setHeadAsset(asset)
      break;
    case AssetType.EYEBROWS:
      setEyebrowsAsset(asset)
      break;
    case AssetType.EYES:
      setEyesAsset(asset)
      break;
    case AssetType.NOSE:
      setNoseAsset(asset)
      break;
    case AssetType.MOUTH:
      setMouthAsset(asset)
      break;
  }

  if (!avatar.value) return;

  emit('select', type, asset, avatar.value);
}

onInit(() => {
  if (!store.value || !assets.value) return;

  setAvatar({
    head: assets.value.head[0],
    eyebrows: assets.value.eyebrows[0],
    eyes: assets.value.eyes[0],
    nose: assets.value.nose[0],
    mouth: assets.value.mouth[0],
  })
})
</script>

<template>
  <slot name="renderer" :ref="canvas">
    <AvatarRenderer ref="canvas" :width="props.width" :height="props.height" />
  </slot>
  <slot name="selector" :assets="assets" :setHeadAsset="setHeadAsset" :setEyebrowsAsset="setEyebrowsAsset" :setEyesAsset="setEyesAsset" :setMouthAsset="setMouthAsset" :setNoseAsset="setNoseAsset">
    <AssetSelector v-if="assets" :assets="assets" :selected="avatar" @select="handleSelect" />
  </slot>
</template>
