// packages/react/components/tabs/tabs-content.tsx
import React from "react";

interface TabsContentProps {
  value: string;
  activeTab: string;
  children: React.ReactNode;
}

export default function TabsContent(props: TabsContentProps) {
  const { value, activeTab, children } = props;
  const isActive = activeTab === value;

  if (!isActive) return null;

  return <div>{children}</div>;
}

// packages/vue/src/components/tabs/TabsContent.vue
<script setup lang="ts">
import { inject, defineProps, computed, Ref } from 'vue';

const props = defineProps<{
  value: string;
}>();

const activeTab: Ref<string> | undefined = inject('activeTab');

const isActive = computed(() => activeTab?.value === props.value);
</script>

<template>
  <div v-if="isActive">
    <slot></slot>
  </div>
</template>
